galaxy_info:
  author: Erik Kaareng-Sunde
  description: Installs step-ca cli for certificate management

  license: Apache-2.0

  min_ansible_version: 2.10
  
  platforms:
  - name: Ubuntu
    versions:
    - 20.04

  galaxy_tags:
    - step-ca
    - certificates
    - ssl
    - CA

  dependencies: 
  - community.docker
